"""
OSCAR Vault Client - External Database Credential Resolution

This module provides integration with OSCAR's HashiCorp Vault for managing
database connection credentials. Instead of storing credentials directly in
MindsDB's Integration table, users can reference credentials managed in OSCAR Vault.

Features:
- Fetch credentials from OSCAR Vault via middleware API
- Thread-safe credential caching with configurable TTL
- Support for multiple database engines with handler-specific field mapping
- Automatic detection and conversion of OSCAR registry shape credentials

Usage:
    from mindsdb.utilities.oscar_vault import (
        resolve_connection,
        validate_connection_exists,
        OSCAR_VAULT_ENABLED
    )

    if OSCAR_VAULT_ENABLED:
        credentials = resolve_connection("prod_mysql", "mysql")

Configuration (via Config() - set by config_validator.py from env vars):
    KORE_OSCAR_VAULT_ENABLED - Enable Vault integration (default: false)
    KORE_OSCAR_VAULT_MIDDLEWARE_URL - OSCAR middleware URL (default: https://middleware:5200)
    KORE_OSCAR_VAULT_CACHE_TTL - Cache TTL in seconds, 0 for strict freshness (default: 60)
    KORE_OSCAR_VAULT_SSL_VERIFY - SSL certificate verification (default: false)
"""

import json
import threading
import time
from typing import Any, Dict, Optional
from urllib.parse import unquote

import requests

from mindsdb.utilities import log
from mindsdb.utilities.config import Config
from mindsdb.utilities.exception import MindsDBError


logger = log.getLogger(__name__)


# =============================================================================
# Exception Classes
# =============================================================================


class OscarVaultError(MindsDBError):
    """Base exception for OSCAR Vault errors.

    Attributes:
        message (str): Error message
        connection_id (str): Connection identifier that caused the error
    """

    def __init__(self, message: str, connection_id: str = None) -> None:
        self.message = message
        self.connection_id = connection_id or "unknown"
        super().__init__(message)

    def __str__(self) -> str:
        return f"{self.message}: {self.connection_id}"


class ConnectionNotFoundError(OscarVaultError):
    """Raised when a connection_id does not exist in OSCAR Vault."""

    def __init__(self, message: str = None, connection_id: str = None) -> None:
        if message is None:
            message = "Connection not found in OSCAR Vault"
        super().__init__(message, connection_id)


class VaultConnectionError(OscarVaultError):
    """Raised when unable to connect to OSCAR Vault/middleware."""

    def __init__(self, message: str = None, connection_id: str = None) -> None:
        if message is None:
            message = "Unable to connect to OSCAR Vault"
        super().__init__(message, connection_id)


# =============================================================================
# Configuration (from Config() - populated by config_validator.py)
# =============================================================================


def _get_vault_config() -> Dict[str, Any]:
    """Get OSCAR Vault configuration from Config().

    Config() merges: defaults → config.json → config.auto.json → env vars → CLI args
    The config.json is generated by config_validator.py from KORE_* env vars.
    """
    config = Config()
    vault_config = config.get("oscar_vault", {})

    if not vault_config.get("enabled", False):
        return {"enabled": False, "middleware_url": "https://middleware:5200", "cache_ttl": 60, "ssl_verify": False}

    return vault_config


# Module-level config (loaded once at import time)
_config = _get_vault_config()
OSCAR_VAULT_ENABLED = _config.get("enabled", False)
OSCAR_MIDDLEWARE_URL = _config.get("middleware_url", "https://middleware:5200")
OSCAR_VAULT_CACHE_TTL = _config.get("cache_ttl", 60)
OSCAR_SSL_VERIFY = _config.get("ssl_verify", False)  # Already a boolean from config_validator


# =============================================================================
# Thread-Safe Cache
# =============================================================================

_cache: Dict[str, tuple] = {}
_cache_lock = threading.Lock()


def _get_from_cache(connection_id: str) -> Optional[Dict[str, Any]]:
    """Get credentials from cache if still valid.

    Args:
        connection_id: The connection identifier

    Returns:
        Cached credentials dict if valid, None if expired or not found
    """
    with _cache_lock:
        if connection_id in _cache:
            data, timestamp = _cache[connection_id]
            if OSCAR_VAULT_CACHE_TTL > 0 and (time.time() - timestamp) < OSCAR_VAULT_CACHE_TTL:
                logger.debug(f"Cache hit for connection '{connection_id}'")
                return data
            # Cache expired, remove entry
            del _cache[connection_id]
            logger.debug(f"Cache expired for connection '{connection_id}'")
    return None


def _set_cache(connection_id: str, data: Dict[str, Any]) -> None:
    """Store credentials in cache with timestamp.

    Args:
        connection_id: The connection identifier
        data: Credentials data to cache
    """
    if OSCAR_VAULT_CACHE_TTL <= 0:
        # Cache disabled (strict freshness mode)
        return

    with _cache_lock:
        _cache[connection_id] = (data, time.time())
        logger.debug(f"Cached credentials for connection '{connection_id}'")


def clear_cache(connection_id: Optional[str] = None) -> None:
    """Clear cached credentials.

    Args:
        connection_id: Specific connection to clear, or None to clear all
    """
    with _cache_lock:
        if connection_id is None:
            _cache.clear()
            logger.debug("Cleared all cached credentials")
        elif connection_id in _cache:
            del _cache[connection_id]
            logger.debug(f"Cleared cached credentials for '{connection_id}'")


# =============================================================================
# Credential Shape Detection and Mapping
# =============================================================================


def is_registry_shape(credentials: Dict[str, Any]) -> bool:
    """Detect if credentials are in OSCAR registry format vs handler format.

    OSCAR stores connections in "registry shape" with fields like:
    - conn_type, login, schema, extra (JSON string)

    MindsDB handlers expect "handler shape" with fields like:
    - user, database (varies by handler)

    Args:
        credentials: The credentials dictionary from Vault

    Returns:
        True if credentials are in registry shape, False otherwise
    """
    registry_keys = ("conn_type", "login", "schema")
    return any(k in credentials for k in registry_keys)


def _parse_extra(extra: Any, engine: str) -> Dict[str, Any]:
    """Parse extra JSON string and extract whitelisted keys per engine.

    Args:
        extra: The extra field (may be string or dict)
        engine: The database engine name

    Returns:
        Dictionary of whitelisted extra fields
    """
    if isinstance(extra, str):
        try:
            extra = json.loads(extra)
        except json.JSONDecodeError:
            logger.debug(f"Failed to parse extra field as JSON: {extra[:50] if extra else 'empty'}")
            return {}

    if not isinstance(extra, dict):
        return {}

    # Engine-specific whitelists
    ssl_keys = {"ssl_ca", "ssl_cert", "ssl_key", "ssl_disabled"}

    if engine in ("mysql", "mariadb"):
        whitelist = ssl_keys | {"charset"}
    elif engine == "postgres":
        whitelist = ssl_keys | {"sslmode"}
    else:
        whitelist = ssl_keys

    return {k: v for k, v in extra.items() if k in whitelist}


def map_registry_to_handler(credentials: Dict[str, Any], engine: str) -> Dict[str, Any]:
    """Convert OSCAR registry shape to MindsDB handler shape.

    Registry Shape (Vault storage):
        conn_type, host, port, login, password, schema, extra, description

    Handler Shape (MindsDB expects):
        host, port, user, password, database (varies by handler)

    Args:
        credentials: Registry-shape credentials from Vault
        engine: Target database engine

    Returns:
        Handler-shape credentials dict
    """
    out: Dict[str, Any] = {}

    # Common fields (passthrough)
    if credentials.get("host"):
        out["host"] = credentials["host"]
    if credentials.get("port"):
        out["port"] = credentials["port"]
    if credentials.get("password"):
        out["password"] = credentials["password"]

    # Engine-specific mapping (handler key takes precedence over registry key)
    engine_lower = engine.lower()

    if engine_lower in ("mysql", "mariadb", "postgres", "mssql"):
        out["user"] = credentials.get("user") or credentials.get("login")
        out["database"] = credentials.get("database") or credentials.get("schema")
    elif engine_lower == "mongodb":
        out["username"] = credentials.get("username") or credentials.get("login")
        out["database"] = credentials.get("database") or credentials.get("schema")
    elif engine_lower == "oracle":
        out["user"] = credentials.get("user") or credentials.get("login")
        out["service_name"] = credentials.get("service_name") or credentials.get("schema")

    # Parse and merge extra fields
    extra_fields = _parse_extra(credentials.get("extra"), engine_lower)
    out.update(extra_fields)

    # Filter out None values
    return {k: v for k, v in out.items() if v is not None}


# Handler field mappings for legacy handler-shape credentials
HANDLER_FIELD_MAPPINGS = {
    "mysql": {"user": "user", "database": "database"},
    "mariadb": {"user": "user", "database": "database"},
    "postgres": {"user": "user", "database": "database"},
    "mongodb": {"username": "username", "database": "database"},
    "mssql": {"user": "user", "database": "database"},
    "oracle": {"user": "user", "service_name": "service_name"},
}


def map_credentials_to_handler(credentials: Dict[str, Any], engine: str) -> Dict[str, Any]:
    """Map credentials to handler-expected field names.

    This handles credentials already in handler-like shape but may need
    minor field name adjustments.

    Args:
        credentials: Credentials dict from Vault
        engine: Database engine name

    Returns:
        Credentials dict with handler-expected field names
    """
    engine_lower = engine.lower()
    mapping = HANDLER_FIELD_MAPPINGS.get(engine_lower, {})

    result = {}
    for key, value in credentials.items():
        if key in mapping:
            result[mapping[key]] = value
        else:
            result[key] = value

    return result


# =============================================================================
# External Connection Storage Validation
# =============================================================================

# Whitelist of allowed keys for external connection storage
# This prevents accidental credential storage in external connection records
EXTERNAL_CONNECTION_ALLOWED_KEYS = frozenset(
    {
        "connection_id",  # Required: Vault connection identifier
        "external",  # Required: Flag indicating external connection
        "type",  # Optional: Database type hint
        "description",  # Optional: User-provided description
    }
)


def validate_external_storage_data(storage_data: Dict[str, Any]) -> None:
    """Validate that external connection storage data contains only allowed keys.

    External connections should store ONLY a reference to Vault credentials,
    never the credentials themselves. This validation enforces that contract.

    Args:
        storage_data: The data dict to be stored in Integration.data

    Raises:
        OscarVaultError: If storage_data contains keys not in the whitelist
    """
    if not isinstance(storage_data, dict):
        raise OscarVaultError(
            "External connection storage_data must be a dictionary",
            storage_data.get("connection_id") if isinstance(storage_data, dict) else "(invalid)",
        )

    unexpected_keys = set(storage_data.keys()) - EXTERNAL_CONNECTION_ALLOWED_KEYS
    if unexpected_keys:
        raise OscarVaultError(
            f"External connections cannot contain keys: {sorted(unexpected_keys)}. "
            f"Allowed keys: {sorted(EXTERNAL_CONNECTION_ALLOWED_KEYS)}",
            storage_data.get("connection_id", "(unknown)"),
        )

    # Ensure required keys are present
    if not storage_data.get("connection_id"):
        raise OscarVaultError("External connection must have a connection_id", "(missing)")
    if not storage_data.get("external"):
        raise OscarVaultError(
            "External connection must have external=True", storage_data.get("connection_id", "(unknown)")
        )


# =============================================================================
# Vault API Client
# =============================================================================


def fetch_connection_credentials(connection_id: str) -> Dict[str, Any]:
    """Fetch connection credentials from OSCAR Vault.

    Args:
        connection_id: The connection identifier in Vault

    Returns:
        Raw credentials dict from Vault

    Raises:
        OscarVaultError: If Vault integration is disabled or connection_id is empty
        ConnectionNotFoundError: If connection_id doesn't exist
        VaultConnectionError: If unable to reach Vault or invalid response
    """
    # Validate connection_id is non-empty
    if not connection_id or not connection_id.strip():
        raise OscarVaultError("connection_id cannot be empty", connection_id or "(empty)")

    if not OSCAR_VAULT_ENABLED:
        raise OscarVaultError(
            "OSCAR Vault integration is disabled. Set KORE_OSCAR_VAULT_ENABLED=true to use external connections",
            connection_id,
        )

    # Check cache first
    cached = _get_from_cache(connection_id)
    if cached is not None:
        return cached

    # Build Workflows Connections API request
    # This endpoint fetches connection credentials from OSCAR's Airflow connections stored in Vault
    url = f"{OSCAR_MIDDLEWARE_URL}/api/v1/workflows/connections/{connection_id}"
    params = {"include_credentials": "true"}
    headers = {"X-Internal-Service": "kore", "Content-Type": "application/json"}

    logger.debug(f"Fetching credentials from OSCAR Workflows: connection_id={connection_id}")

    try:
        response = requests.get(url, params=params, headers=headers, verify=OSCAR_SSL_VERIFY, timeout=10)

        if response.status_code == 404:
            raise ConnectionNotFoundError(f"Connection '{connection_id}' not found in OSCAR Workflows", connection_id)

        if response.status_code != 200:
            raise VaultConnectionError(
                f"OSCAR Workflows API returned status {response.status_code}: {response.text[:200]}", connection_id
            )

        # Parse JSON response - handle non-JSON responses gracefully
        try:
            credentials = response.json()
        except ValueError as e:
            raise VaultConnectionError(f"Invalid JSON response from OSCAR Workflows API: {str(e)}", connection_id)

        # URL-decode the password field if present (Airflow connections store URL-encoded passwords)
        if credentials.get("password"):
            credentials["password"] = unquote(credentials["password"])

        # Cache the credentials
        _set_cache(connection_id, credentials)

        logger.info(f"Fetched credentials from OSCAR Workflows for connection '{connection_id}'")
        return credentials

    except requests.exceptions.ConnectionError as e:
        raise VaultConnectionError(
            f"Unable to connect to OSCAR middleware at {OSCAR_MIDDLEWARE_URL}: {str(e)}", connection_id
        )
    except requests.exceptions.Timeout:
        raise VaultConnectionError(f"Timeout connecting to OSCAR middleware at {OSCAR_MIDDLEWARE_URL}", connection_id)
    except requests.exceptions.RequestException as e:
        raise VaultConnectionError(f"Error fetching credentials from OSCAR Workflows: {str(e)}", connection_id)


def validate_connection_exists(connection_id: str) -> bool:
    """Validate that a connection exists in OSCAR Vault.

    Args:
        connection_id: The connection identifier to validate

    Returns:
        True if connection exists

    Raises:
        OscarVaultError: If Vault integration is disabled
        ConnectionNotFoundError: If connection doesn't exist
        VaultConnectionError: If unable to reach Vault
    """
    # This will raise appropriate exceptions if connection doesn't exist
    fetch_connection_credentials(connection_id)
    return True


def resolve_connection(connection_id: str, engine: str) -> Dict[str, Any]:
    """Resolve connection credentials from OSCAR Vault.

    Fetches credentials from Vault, detects the credential shape,
    and converts to handler-expected format if needed.

    Args:
        connection_id: The connection identifier in Vault
        engine: Target database engine (e.g., "mysql", "postgres")

    Returns:
        Handler-ready credentials dict

    Raises:
        OscarVaultError: If Vault integration is disabled
        ConnectionNotFoundError: If connection doesn't exist
        VaultConnectionError: If unable to reach Vault
    """
    if not OSCAR_VAULT_ENABLED:
        raise OscarVaultError(
            f"OSCAR Vault integration is disabled. Set KORE_OSCAR_VAULT_ENABLED=true "
            f"to use external connections with connection_id='{connection_id}'",
            connection_id,
        )

    # Fetch raw credentials from Vault
    credentials = fetch_connection_credentials(connection_id)

    # Detect and convert credential shape
    if is_registry_shape(credentials):
        # Warn on engine mismatch
        vault_engine = credentials.get("conn_type", "").lower()
        if vault_engine and vault_engine != engine.lower():
            logger.warning(
                f"Engine mismatch: CREATE DATABASE specified '{engine}' but "
                f"Vault connection '{connection_id}' has conn_type '{credentials['conn_type']}'. "
                f"Using '{engine}' as specified."
            )
        return map_registry_to_handler(credentials, engine)
    else:
        # Already in handler shape - apply minor field mapping if needed
        return map_credentials_to_handler(credentials, engine)
